/**
 * Offline shell for the web build, generated by scripts/build-service-worker.mjs with this build's file
 * list baked in. The native app never registers it: Android ships updates through capgo, and a second
 * cache layer inside the WebView would keep serving the pre-OTA files.
 *
 * A new build installs quietly and waits. It never calls skipWaiting on its own, so an update can never
 * swap the files out from under a battle in progress — the page asks for the handover instead, at launch
 * or when the player presses 立即更新. Without that message the waiting worker would sit there forever:
 * reloading the page does not release the old worker, so "takes over next launch" was never actually true.
 */
const CACHE = 'windward-0.5.1-ota3-c11bc371d2c2';
const ASSETS = [
  "./assets/ArenaScene-ByKIVKSL.js",
  "./assets/index-BE_uG27f.css",
  "./assets/index-BZ1X1VRm.js",
  "./assets/index-DjSVKbGL.js",
  "./assets/index-YPsLZj6M.js",
  "./assets/phaser-B8p8Giq7.js",
  "./assets/phaser-DFK5Ua9d.js",
  "./assets/web-B9doIemy.js",
  "./assets/web-BI-54hTp.js",
  "./assets/web-C8V0s13J.js",
  "./assets/web-DZmA6VMS.js",
  "./favicon.svg",
  "./guide/builds.html",
  "./guide/endgame.html",
  "./guide/enemies.html",
  "./guide/gear.html",
  "./guide/index.html",
  "./guide/passives.html",
  "./guide/skills.html",
  "./icons/windward-180.png",
  "./icons/windward-192.png",
  "./icons/windward-512.png",
  "./icons/windward-64.png",
  "./index.html",
  "./manifest.webmanifest",
  "./portraits/assassin.png",
  "./portraits/druid.png",
  "./portraits/mage.png",
  "./portraits/necromancer.png",
  "./portraits/ranger.png",
  "./portraits/summoner.png",
  "./portraits/warrior.png"
];

// 绕过浏览器的 HTTP 缓存直接向服务器要：GitHub Pages 会让 index.html 缓存十分钟，照常请求可能拿到上一版的
// index.html，而它引用的带哈希资源在发布时已经删了——新版本就会一直用这份旧外壳白屏，直到下一次发版。
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS.map(url => new Request(url, { cache: 'reload' })))));
});

// 页面在安全的时刻（启动，或玩家主动点更新）发来这条消息，等待中的版本才接管。
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(name => name.startsWith('windward-') && name !== CACHE).map(name => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const { request } = event;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  // 图鉴是独立的多页静态站，不能套用游戏的单页外壳，否则打开 /guide/ 会看到游戏本身。
  // 目录形式的地址要落到具体页面，缓存里存的是 guide/index.html 这样的路径；少了结尾斜杠的 /guide
  // 得先补上斜杠，直接把 index.html 发回去的话，页内的 ../icons 和 skills.html 全会指到上一层去。
  if (/\/guide(\/|$)/.test(url.pathname)) {
    const directory = request.mode === 'navigate' && !/\.[^/]+$/.test(url.pathname);
    if (directory && !url.pathname.endsWith('/')) {
      event.respondWith(Response.redirect(`${url.origin}${url.pathname}/${url.search}`, 302));
      return;
    }
    event.respondWith(serve(directory ? `${url.origin}${url.pathname}index.html` : request, request));
    return;
  }
  // The game is a single page with no routing, so every navigation resolves to the cached shell.
  event.respondWith(request.mode === 'navigate' ? serve('./index.html', request) : serve(request, request));
});

/** Content-hashed assets never change under the same name, so the cache always wins when it has a copy. */
async function serve(key, request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(key);
  if (cached) return cached;
  try {
    return await fetch(request);
  } catch {
    return new Response('离线状态下无法获取该资源', { status: 504, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  }
}
